language: php
php:
  - 7.0
  - 7.1
  - 7.2

script: 
 - composer install
 - mkdir -p build/logs
 - php vendor/atoum/atoum/bin/atoum -c travis-coverage.php

after_script:
 - php vendor/bin/coveralls -v
